dist: trusty
sudo: false
addons:
  apt:
    sources:
      - git-core
    packages:
      - git
  ssh_known_hosts:
    secure: "PkrPvXze9Qf2P4jXWlgXAQOriSbDdPuMSZdQArnQ70rZg63V4djPf3vHACo6Ia1ld+672w0QyFuXBWfmGAwE+oloFxS2n2jwwYyVgYKkoKevgOf5Ur084ToxnqdC9fyRWABIRTY6lZzgaxv8pv5yb/nzVhsR1kI0CiRtTwnJ9eSN3fbKfEhEQpw7VpN9ttiudtRBKaJlDlPhwuYi65JMSIqxx3saa3Ew2jkmhhvwzfwfy6TZfIg9Asq1w6yj7HAmSPNOOiqK2ouOq7vapv4RNksCguaALnouWfgkYCrxufTxcyS+EpYMaXBUsVJ4mAdcc0hjIfpxhdtD9DVHZ6wQnMwkv6m9EOXsapzqOe5A+Z3kW35sMWrtvlnN94Ui841BVDoA2lTmm1q8lsjV9QxxM40RsVlRNMUq+ESnmWiBlUnkY6782fH5t4aALyJuKYSGHZ8r9b2r/IXJGohGSmD/KSbvlhcCzaEMjDdUePBINEtv+9b7R7aBw2tj/4HGqVZKyGmmFjlsGsdv41Fraa2IpDtRT0Y8mi+gLwQHKXzGKMFceZY6pxb8N4Uvl50S3upCOTzHyuIEhBxbAqxCFnf+6FZn4XOvS2C0JH9tD5AZw2W4y8QWx4d6GCZdq0q6dzLgVuil5j9CfpKUkTEDQ7Py4vRwxbwAcUpPWIHKwaV0lMg="
before_install:
  - openssl aes-256-cbc -K $encrypted_e84bcff1151e_key -iv $encrypted_e84bcff1151e_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d
install: skip
jobs:
  include:
  - stage: deploy
    script: bash ./.travis/deploy.sh
stages:
- name: deploy
  if: (branch = live) AND (type != pull_request)
script: skip